# Generated by Django 5.1.3 on 2024-12-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro_api', '0002_restaurant_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='capacity',
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro_api.restaurant')),
            ],
        ),
    ]
