# Generated by Django 5.1.3 on 2024-12-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro_api', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_people',
            new_name='num_of_people',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='tables',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='working_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='slot',
            name='tables',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
